name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m

    runs-on: ubuntu-latest
    timeout-minutes: 100

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create empty google-services.json
        run: cat /home/runner/work/fitmeter/fitmeter/app/google-services.json | base64

      - name: Putting data into google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/fitmeter/fitmeter/app/google-services.json

      - name: Build with Gradle
        run: ./gradlew build

#      # Step 3: Check the code with ktlint, you can remove this job if you don't use ktlint
#      - name: Run Kotlin Linter
#        run: ./gradlew ktlintDebugCheck
#
#      # Step 3: Check the code with Android linter
#      - name: Run Android Linter
#        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test report directory
        uses: actions/upload-artifact@v4
        with:
          name: testDebugUnitTest
          path: app/build/reports/tests/testDebugUnitTest/
          retention-days: 1

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          detailed_summary: true
          annotate_notice: true
          include_passed: true
          follow_symlink: true
          report_paths: |
            **/build/test-results/test*/**/*.xml

#      # Step 4: Run instrumented tests on firebase test lab
#      - name: Run tests on Firebase Test Lab
#        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#        with:
#          arg-spec: '.github/test-lab-config-staging.yml:android-pixel-4'
#        env:
#          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
