name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check 1
        run: ls /home/runner
      - name: Check 2
        run: ls /home/runner/work
      - name: Check 4
        run: ls /home/runner/work/fitmeter
      - name: Check 5
        run: ls /home/runner/work/fitmeter/tree
      - name: Check 6
        run: ls /home/runner/work/fitmeter/tree/main
      - name: Check 7
        run: ls /home/runner/work/fitmeter/tree/main/app
      - name: Create empty google-services.json
        run: cat /home/runner/work/fitmeter/tree/main/app/google-services.json | base64
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/teanlime/fitmeter/tree/main/app/google-services.json
      - name: Build with Gradle
        run: ./gradlew build
